export default {
    INITIALIZE_STATE: 'INITIALIZE_STATE',
    INITIALIZE_REQUEST: 'INITIALIZE_REQUEST',
    LOAD_DATA_SUCCESS: 'LOAD_REQUEST_SUCCESS',
    LOAD_DATA_FAILURE: 'LOAD_DATA_FAILURE',
    USER_LOGOUT: 'USER_LOGOUT'
}