export default {
    PASSWORD_RESET_REQUEST: 'PASSWORD_RESET_REQUEST',
    PASSWORD_RESET_SUCCEEDED: 'PASSWORD_RESET_SUCCEEDED',
    PASSWORD_RESET_FAILED: 'PASSWORD_RESET_FAILED',
    VERIFY_TOKEN_SUCCEEDED: 'VERIFY_TOKEN_SUCCEEDED',
    VERIFY_TOKEN_FAILED: 'VERIFY_TOKEN_FAILED',
    CHANGE_PASSWORD_SUCCEEDED: 'CHANGE_PASSWORD_SUCCEEDED',
    CHANGE_PASSWORD_FAILED: 'CHANGE_PASSWORD_FAILED'
}