const TaskConstants = {
    TASK_LIST_REQUEST: 'TASK_LIST_REQUEST',
    TASK_LIST_SUCCESS: 'TASK_LIST_SUCCESS',
    TASK_LIST_ERROR: 'TASK_LIST_ERROR',
    UPDATE_TASK_REQUEST: 'UPDATE_TASK_REQUEST',
    UPDATE_TASK_SUCCESS: 'UPDATE_TASK_SUCCESS',
    UPDATE_TASK_ERROR: 'UPDATE_TASK_ERROR'
};

export default TaskConstants