const VoterContants = {
	VOTER_INIT_REQUEST: 'VOTER_INIT_REQUEST',
	VOTER_IMPORT_LIST_REQUEST: 'VOTER_IMPORT_LIST_REQUEST',
	VOTER_IMPORT_LIST_SUCCESS: 'VOTER_IMPORT_LIST_SUCCESS',
	VOTER_IMPORT_LIST_ERROR: 'VOTER_IMPORT_LIST_ERROR',
	VOTER_LIST_SUCCESS: 'VOTER_LIST_SUCCESS',
	VOTER_LIST_ERROR: 'VOTER_LIST_ERROR',
	VOTER_TASK_LIST_SUCCESS: 'VOTER_TASK_LIST_SUCCESS',
	VOTER_TASK_LIST_ERROR: 'VOTER_TASK_LIST_ERROR',
	VOTER_UPDATE_SUCCESS: 'VOTER_UPDATE_SUCCESS',
	VOTER_UPDATE_ERROR: 'VOTER_UPDATE_ERROR',
	VOTER_UPLOAD_FILE_SUCCESS: 'VOTER_UPLOAD_FILE_SUCCESS',
	VOTER_UPLOAD_FILE_FAILURE: 'VOTER_UPLOAD_FILE_FAILURE',
	VOTER_IMPORT_SOCIAL_REQUEST: 'VOTER_IMPORT_SOCIAL_REQUEST',
	VOTER_IMPORT_SOCIAL_SUCCESS: 'VOTER_IMPORT_SOCIAL_SUCCESS',
	VOTER_IMPORT_SOCIAL_FAILURE: 'VOTER_IMPORT_SOCIAL_FAILURE'
};

export default VoterContants